### PR TITLE
Use float input for gain

### PR DESCRIPTION
**Pull request by HEnquist**
fixes https://github.com/HEnquist/camillagui/issues/79

### CODE REVIEW

**Comment by JWahle** [comment]
This seems to be already present in the `next20` branch.
Can we just close this PR?

**Comment by HEnquist** [comment]
I was going to merge this and release a fixed gui version for v1.0. Just need to find the time..

**Comment by JWahle** [comment]
Ah, alright

**Comment by HEnquist** [comment]
2.0 is released, closing this

**Pull request closed without merging**
