### PR TITLE
Undo/Redo

### PR DESCRIPTION
**Pull request by JWahle**
@HEnquist I just implemented two arrows in the tab bar to undo/redo recent changes, including a tooltip, that shows what changed.
Can you try the functionality and see, if it works as you would expect?

### CODE REVIEW

**Comment by HEnquist** [comment]
Seems to work just fine! A small annoying detail was that it selected text on the page every time I "double-clicked" a button, for example when undoing two changes. I made a simple fix to that by just disabling user-select on all buttons. If you are happy with this we can merge.

**Comment by HEnquist** [comment]
Just noticed that it's not possible to create mixers in this branch.
To reproduce the problem, just go to the mixers tab, add a new mixer, and then press the + button to add either a mapping or a source. 
Error: 
```
Uncaught RangeError: Maximum call stack size exceeded
    at jsonDiffAsLines (jsondiff.ts:15:1)
    at jsondiff.ts:57:1
    at Array.map (<anonymous>)
    at getChildrenDiffs (jsondiff.ts:57:1)
    at jsonDiffAsLines (jsondiff.ts:15:1)
    at jsondiff.ts:57:1
    at Array.map (<anonymous>)
    at getChildrenDiffs (jsondiff.ts:57:1)
    at jsonDiffAsLines (jsondiff.ts:15:1)
    at jsondiff.ts:57:1
    at Array.map (<anonymous>)
    at getChildrenDiffs (jsondiff.ts:57:1)
    at jsonDiffAsLines (jsondiff.ts:15:1)
    at jsondiff.ts:57:1
(etc etc)
```

**Comment by JWahle** [comment]
I'm glad, you found that one before the release.
I'll have a look.

**Comment by JWahle** [comment]
It is fixed now.

**Comment by HEnquist** [comment]
Yes, works great now!

**Pull request merged**
