### PR TITLE
Updated version of PR #34 (JWahle Extracted CSS variables) from this repo

### PR DESCRIPTION
**Pull request by JWahle**
This is an updated version of PR #34 on the `gui-style` branch of this repo, so you can commit your additional changes here.

### CODE REVIEW

**Comment by HEnquist** [comment]
Done! I updated both the dark and the bright themes. The dark one looks great now and should definitely be the default.

**Comment by HEnquist** [comment]
You can merge this to develop if you want, or if you want to tweak it a little more and then merge, that's also fine.

**Comment by JWahle** [comment]
I just fixed some small issues:
- tab buttons now also have the same border as the other boxes
- dark skin highlighted button & input focus borders are now also 2px (same as all the other borders)
- Centered small button icon (was dependent on border size before)

**Comment by JWahle** [comment]
@bitkeeper in the [moOde-style](https://github.com/HEnquist/camillagui/compare/moOde-style) branch I committed  a version of css-variables.css customized to look like the default moOde style.
I also added the `--accent-color` variable for the accent color chosen by the moOde user.
If you keep this updated, the CamillaGUI should look pretty similar to the rest of moOde.

**Comment by bitkeeper** [comment]
Thanks guys! I'm very happy with the end result.
And I have also updated the moOde code to change the accent coloor of camillagui:

moode_cdsp_themed

**Pull request merged**
