### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by HEnquist**
Here is a mixed list of things that would be nice to sort out for the next release.

- Plots use easier numbers on x-scale, but they have too many zeros and get drawn on top of each other. There are more numbers than needed, half can be removed. And the ones above 1000 can be shortened, 1000 -> 1k etc
-  "Config" box on the files tab lists everything in the config dir. Show only .yml and .yaml? 
- The upload buttons in File change symbol after an upload, and never change back. I think it's enough that the new file shows up in the list.
- There seems to be a limit of about 1MB for the files uploaded via the Files tab. This is pretty big, but a long filter in f64 could be larger than that. (when running with "npm start", check a production build too).
- Clicking on a file in the Files tab should open the link in a new browser tab
- Saving a config to file should not set it as active. It's perfectly valid to save to file and not having it as active. See also https://github.com/HEnquist/camillagui-backend/issues/22

### CODE REVIEW

**Comment by HEnquist** [comment]
ping @JWahle

**Comment by JWahle** [comment]
I'll have a look this weekend.

**Comment by JWahle** [comment]
> Plots use easier numbers on x-scale, but they have too many zeros and get drawn on top of each other. There are more numbers than needed, half can be removed. And the ones above 1000 can be shortened, 1000 -> 1k etc

I already removed a lot of the labels in the gui-style branch. I had a look at it again and changed it to just have labels for 10, 100, 1k, 10k. How about this? (This change is only in the new `gui-style` branch on this repo)
Filter-plot-new

> "Config" box on the files tab lists everything in the config dir. Show only .yml and .yaml?

I also thought about this, however I have already uploaded files to the wrong folder (filters in the config folder and vice versa) and I like, that I don't have to ssh to the machine to clean up.
Do you see any cases, where it would be beneficial to have some residual files in the config folder?
If not, I would suggest, we leave it, as it is.

> The upload buttons in File change symbol after an upload, and never change back. I think it's enough that the new file shows up in the list.

Seems reasonable - especially after I changed the GUI to update immediately after an upload.
I pushed a change with this to `develop`.

> There seems to be a limit of about 1MB for the files uploaded via the Files tab. This is pretty big, but a long filter in f64 could be larger than that. (when running with "npm start", check a production build too).

> Clicking on a file in the Files tab should open the link in a new browser tab

Fixed in the `develop` branch.

> Saving a config to file should not set it as active. It's perfectly valid to save to file and not having it as active. See also HEnquist/camillagui-backend#22

Will be fixed in the ticket, you mentioned.

**Comment by HEnquist** [comment]
Took another look now.
- Good argument for listing all files, let's leave it like it is.
- Upload button is good now.
- The new smaller labels on frequency axis are great. 

All in all it's a huge improvement compared to the previous release, thank you for doing all this!

**Comment by JWahle** [comment]
You're welcome - thank you for CDSP :)

I increased the 1MB limit to 1GB - this should be enough for "most" filters. The fix is in the backend's `develop` branch.

The only point still open is HEnquist/camillagui-backend#22 and that is in the backend. So I think, we're ready to merge here.

**Comment by JWahle** [comment]
@HEnquist please check my latest commits and merge, if you find nothing suspicious.
I'll soon take care of HEnquist/camillagui-backend#22.

**Pull request merged**
