### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by HEnquist**

### CODE REVIEW

**Comment by HEnquist** [comment]
I want to start wrapping up the gui for camilladsp 1.0.0. 
@JWahle and  @bitkeeper, would it make sense to make a gui release with the changes here for 0.6.3 before changing focus to 1.0.0?

**Comment by bitkeeper** [comment]
@HEnquist depends on your planning. @JWahle created some nice enhancements. If you planning to release a gui (rc) for camilldsp 1.0.0 (rc) version very soon, I would skip an additional intermediate release. If not maybe an intermediate release would be nice.

**Comment by HEnquist** [comment]
I'm not planning any more changes to camilladsp 1.0.0 before releasing it, only bugfixes if something bad comes up. So the current rc and the final 1.0.0 will work with the same gui and libraries.
In practice, making an intermediate release for 0.6.3 or making one for 1.0.0(rc) will take about the same amount of time. If there are no specific reasons for making intermediate release for 0.6.3, I'd prefer to save some time by skipping it. Then I can start on the release for 1.0.0 right away.

**Comment by JWahle** [comment]
Skipping the intermediate release would be fine for me.

**Comment by HEnquist** [comment]
Alright, then we skip the intermediate release for 0.6.3. It would be nice to include all the planned features in the release for 1.0.0, but we could also make a prerelease before. Let's see how it goes with available free time etc.

**Pull request merged**
