### PR TITLE
Redesigned sidepanel

### PR DESCRIPTION
**Pull request by JWahle**
I felt like redesigning the Sidepanel and I also fixed some JS warnings.
What do you think?

Sidepanel-redesign

### CODE REVIEW

**Comment by HEnquist** [comment]
Looks much nicer!
Unfortunately it's making it even taller. It was already a bit tall, and now it's easy to make it larger than a normal screen.
Here is a screenshot at 1920x1080 with 2 channels in, 8 channels out:
sidepanel

It would be great if we could fit that somehow. Adding tabs perhaps? There could be a "File" tab and a "Status" tab.

**Comment by JWahle** [comment]
Yeah, the height is definitely a problem - especially, if the `Config status` gets pushed off the screen.

Here is where I see room for improvement:
- CamillaDSP - Message field
    Not sure, if it ever displays relevant information. I don't think I have seen anything other than OK, blank and error 500.
    Can it be just removed?
- Config - Load config from a local file
    I'll try to restyle it to use a simple button, just as the "Save to file" button
- Config - Upload a config/coefficient file
    I think, this would indeed fit a "File" tab really well. I use the other options frequently, so I would leave them as they are.
- Config status
    The information, whether config checking is available could be placed in the "Status" (or "Info"?) tab
    If there is an error, a red box could be should below the tab bar - probably with a red outline of the whole config area, so that errors can't be missed
    If config checking is not available, a subtle warning could be shown below the tab bar
- Versions
    could also be moved to the "Status" tab

What do you think?

**Comment by JWahle** [comment]
How about this?

Sidepanel-redesign4

Here's what I did:
- Redesigned "Get", "Apply", "Save to file", "Load config from a local file" buttons
- Moved buttons to upload configs/coefficients to "Files" tab.
- Moved config check message from "Config status" to "Config" and added intuitive coloration
- Changed versions to small centered labels (hidden, if CDSP is not connected)

**Comment by HEnquist** [comment]
This looks great! I'm stuck fixing a weird issue on macos now, but I'll take a proper look at the changes as soon as I'm done with that. Tomorrow I hope!

**Comment by HEnquist** [comment]
I tested this now, looks and works great. Thanks!

**Pull request merged**
