### PR TITLE
Fixed plot filters step and added nicer labels for frequency axis

### PR DESCRIPTION
**Pull request by JWahle**
Depends on and includes the commit of #25.

### CODE REVIEW

**Comment by bitkeeper** [comment]
After switching to this branch the filters tab isn't accessible anymore. 
Probably something todo with changes in #25?

**Comment by JWahle** [comment]
Yes, the error was because of the unknown `mute` parameter for some filters.
The fix for this was already included in #25.
I just rebased the branch of this PR on #25 - it should work now.

**Comment by HEnquist** [comment]
I didn't have time to look at this yet, sorry. How about simplifying a little. We could keep master equal to the latest released (and tagged) version, and let all development until the next release is ready happen on the develop branch. You could merge changes yourself into develop (you should have permission now) instead of making many smaller PRs to master where each one depends on the previous. And same on the backend of course. Then once develop is at a good stage for a new release, then make a PR to master. Once merged, we tag it. When doing that in the backend it will build a release package including the frontend automatically.

**Comment by JWahle** [comment]
@HEnquist I have no problem waiting a couple of days for your review - even if that means to occasionally rebase  to keep the PRs up to date. I lose hardly any time on this.
However, if you prefer me working on the develop without or with much later review, I'm also fine with that.
Just make a decision.

**Comment by HEnquist** [comment]
I think I prefer fewer but larger PRs. But it doesn't make sense to change anything right now, since master is already moving towards the next release. 
Once the next release is out, I would like to switch all development to develop (assuming you want to continue :)). Then for minor improvements or bugfixes, you can just merge them yourself to develop. For big changes it's better to work on a separate branch and then make a PR to develop once the thing is complete. Then it makes sense to open an issue first so we can agree on the general idea before starting. And for stuff in between these two, you can decide for yourself which way makes the most sense.

**Comment by JWahle** [comment]
Alright, that sounds good.
After this, I have two big PRs upcoming for the mixers and pipeline tab, the rest will be rather small changes, which I will then merge to develop.

**Comment by JWahle** [comment]
I just rebased on #25.

**Pull request merged**
